import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Slide, ToastContainer } from "react-toastify";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: "500", style: "normal" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Slide}
        />
        {children}
      </body>
    </html>
  );
}
